# Resume Automation Configuration Template
#
# SETUP INSTRUCTIONS:
# 1. Copy this file to config.yaml: cp config_template.yaml config.yaml
# 2. Replace the following placeholders with your personal information:
#    - {ANTHROPIC_API_KEY}: Your Anthropic API key
#    - {google_service_account_file}: Path to your Google Service Account JSON file
#    - {templates_folder_id}: ID of your Google Drive templates folder
#    - {output_folder_id}: ID of your Google Drive output folder
#    - {cover_letter_template_id}: ID of your Google Drive cover letter template
#    - {drive_for_mac_root}: Path to your Google Drive for Mac sync root
#    - {folder_structure}: Folder structure for your Google Drive output
#    - {resume_filename}: Resume filename format
#    - {cover_letter_filename}: cover letter filename format
#    - {generate_pdf}: whether to generate pdfs
#    - {enable_resume_tracking}: whether to enable resume tracking
#    - {resume_tracking_worksheet}: path to your google drive resume tracking worksheet
#    - {prevent_duplicate_resumes}: whether to prevent duplicate resumes
#    - {name}: your full name
#    - {phone}: your phone number
#    - {email}: your email address
#    - {city_state}: your city and state (e.g., "new york, ny")
#    - {rate_limit_delay}: delay between api calls
#    - {max_retries}: maximum number of retries
#    - {timeout}: api timeout

# Anthropic API Settings
anthropic:
  api_key: ${ANTHROPIC_API_KEY}
  model: "claude-3-5-sonnet-20241022"
  max_tokens: 4000
  temperature: 0.7

# Google Drive Settings
google_drive:
  service_account_file: "service_account.json"
  templates_folder_id: "YOUR_TEMPLATES_FOLDER_ID"  # Replace with your actual folder ID
  output_folder_id: "YOUR_OUTPUT_FOLDER_ID"        # Replace with your actual folder ID
  
  # Baseline resume mapping (file names of your complete resumes in Google Drive)
  baseline_resumes:
    senior_engineering_manager: "Engineering Manager"
    engineering_manager: "Engineering Manager" 
    director: "Engineering Manager"
    data_engineering_manager: "Data Engineering Manager"
    senior_software_engineer: "Software Engineer"
    software_engineer: "Software Engineer"
    lead_data_engineer: "Lead Data Engineer"
    data_engineer: "Data Engineer"
  
  # Default baseline resume when auto-detection fails or confidence is low
  default_baseline_resume: "engineering_manager"
  
  # Cover letter template document ID in Google Drive
  cover_letter_template_id: "YOUR_COVER_LETTER_TEMPLATE_ID"

# Resume Generation Prompts
# Path to YAML file containing prompt definitions
prompts_file: "prompts.yaml"  # Copy prompts_template.yaml to prompts.yaml and customize

# File Organization Settings
file_organization:
  # Google Drive for Mac sync root path
  drive_for_mac_root: "/Users/USERNAME/Library/CloudStorage/GoogleDrive-EMAIL@gmail.com/My Drive"
  folder_structure: "resume-automation-system/ready-for-review/{company_name} - {position_title}/"
  resume_filename: "{name} {position_title} - {company_name}"
  cover_letter_filename: "Cover Letter - {company_name} - {position_title}"
  generate_pdf: true
  
  # Resume tracking settings
  enable_resume_tracking: true
  resume_tracking_worksheet: "resume-automation-system/ready-for-review/resume_tracking.xlsx"
  
  # Duplicate prevention settings
  prevent_duplicate_resumes: true

# User Information - Update with your personal details
user:
  name: "Your Name"
  phone: "Your Phone Number"
  email: "your.email@gmail.com"
  city_state: "Your City, State"

# System Settings
system:
  rate_limit_delay: 1.0  # seconds between API calls
  max_retries: 5
  timeout: 30