# Resume Automation Configuration

# Anthropic API Settings
anthropic:
  api_key: ${ANTHROPIC_API_KEY}
  model: "claude-3-5-sonnet-20241022"
  max_tokens: 4000
  temperature: 0.7

# Google Drive Settings
google_drive:
  service_account_file: "service_account.json"
  templates_folder_id: "1_7v-RMC5OTeYgU8DMel5gWaTOk-b4Ycd"  # Replace with your actual folder ID
  output_folder_id: "1DBUHem5_AyThftJ68l5nacNeJP6pAzb0"        # Replace with your actual folder ID
  
  # Baseline resume mapping (file names of your complete resumes in Google Drive)
  baseline_resumes:
    senior_engineering_manager: "Engineering Manager"
    engineering_manager: "Engineering Manager" 
    director: "Engineering Manager"
    data_engineering_manager: "Data Engineering Manager"
    senior_software_engineer: "Software Engineer"
    software_engineer: "Software Engineer"
    lead_data_engineer: "Lead Data Engineer"
    data_engineer: "Data Engineer"
  
  # Default baseline resume when auto-detection fails or confidence is low
  default_baseline_resume: "engineering_manager"
  
  # Cover letter template document ID in Google Drive
  cover_letter_template_id: "1zORsLwBloXaaBdy7Lq0EJ6dxAMFou2u8klxs1TQ3PSA"

# Resume Generation Prompts
# Path to YAML file containing prompt definitions
# Copy prompts.yaml to {your_name}_prompts.yaml and customize
prompts_file: "jmindek_prompts.yaml"

# File Organization Settings
file_organization:
  # Google Drive for Mac sync root path
  drive_for_mac_root: "/Users/jerrymindek/Library/CloudStorage/GoogleDrive-jerry.mindek@gmail.com/My Drive"
  folder_structure: "resume-automation-system/ready-for-review/{company_name} - {position_title}/"
  resume_filename: "Jerry Mindek {position_title} - {company_name}"
  cover_letter_filename: "Cover Letter - {company_name} - {position_title}"
  generate_pdf: true
  
  # Resume tracking settings
  enable_resume_tracking: true
  resume_tracking_worksheet: "resume-automation-system/ready-for-review/resume_tracking.xlsx"
  
  # Duplicate prevention settings
  prevent_duplicate_resumes: true

# System Settings
system:
  rate_limit_delay: 1.0  # seconds between API calls
  max_retries: 5
  timeout: 30